# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "122b5a91b233bd7c6bff0731dfeedf56"
name = "remix-test-pol"
handle = "remix-test-pol"
application_url = "https://improvements-budgets-express-faq.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tactic-dev-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://improvements-budgets-express-faq.trycloudflare.com/auth/callback",
  "https://improvements-budgets-express-faq.trycloudflare.com/auth/shopify/callback",
  "https://improvements-budgets-express-faq.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
